version: "3.9"
services:
  web:
    build: .
    image: lorna.tv:latest
    container_name: lorna-web
    restart: unless-stopped
    ports:
      - "8080:80"
    # Si Traefik est en place, commente "ports" et décommente les labels + network ci-dessous
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.lorna.rule=Host(`lorna.tv`)"
    #   - "traefik.http.routers.lorna.entrypoints=websecure"
    #   - "traefik.http.routers.lorna.tls.certresolver=letsencrypt"
    # networks:
    #   - proxy
# networks:
#   proxy:
#     external: true
