version: "3.9"
services:
  web:
    build: .
    image: lorna.tv:latest
    container_name: lorna-web
    restart: unless-stopped
    # optional pendant la transition :
    ports:
      - "8080:80"
    networks:
      - proxy
networks:
  proxy:
    external: true
